import UIKit
import KilkariCore

/// The immunisation record, as a PDF a clinic or a school will accept.
///
/// Paginated rather than clipped. A full IAP schedule is thirty-three doses across ten groups
/// and does not fit on one A4 page; a record that quietly stops at the fold is worse than no
/// record, because the parent handing it over has no way to know it is short.
enum VaccinationRecord {

    private enum Layout {
        static let page = CGRect(x: 0, y: 0, width: 595, height: 842)   // A4 at 72dpi
        static let left: CGFloat = 40
        static let right: CGFloat = 555
        static let top: CGFloat = 56
        /// Where the footer starts, and so the last line a row may occupy.
        static let bottom: CGFloat = 790
    }

    private static let title = [
        NSAttributedString.Key.font: UIFont.systemFont(ofSize: 22, weight: .bold),
        .foregroundColor: UIColor(KC.ink),
    ]
    private static let heading = [
        NSAttributedString.Key.font: UIFont.systemFont(ofSize: 12, weight: .bold),
        .foregroundColor: UIColor(KC.tealDeep),
    ]
    private static let body = [
        NSAttributedString.Key.font: UIFont.systemFont(ofSize: 11),
        .foregroundColor: UIColor(KC.ink),
    ]
    private static let muted = [
        NSAttributedString.Key.font: UIFont.systemFont(ofSize: 10),
        .foregroundColor: UIColor(KC.muted),
    ]

    static func pdf(
        babyName: String,
        dob: Date,
        scheduleName: String,
        groups: [VaccineGroupState]
    ) -> Data {
        let renderer = UIGraphicsPDFRenderer(bounds: Layout.page)
        return renderer.pdfData { context in
            var page = 0
            var y: CGFloat = 0

            func newPage() {
                context.beginPage()
                page += 1
                y = Layout.top
                if page == 1 {
                    draw("Immunisation record", at: CGPoint(x: Layout.left, y: y), title)
                    y += 30
                    draw("\(babyName) · born \(Fmt.date(dob))", at: CGPoint(x: Layout.left, y: y), body)
                    y += 16
                    draw("Schedule: \(scheduleName)", at: CGPoint(x: Layout.left, y: y), muted)
                    y += 18
                } else {
                    draw("Immunisation record · \(babyName) · page \(page)",
                         at: CGPoint(x: Layout.left, y: y), muted)
                    y += 20
                }
                rule(at: y, in: context)
                y += 18
            }

            /// Starts a page when the next block would not fit whole.
            func reserve(_ height: CGFloat) {
                if page == 0 || y + height > Layout.bottom { newPage() }
            }

            for group in groups {
                // A heading with no rows under it is a heading at the bottom of a page, so a
                // group claims its title and its first dose together or moves on.
                reserve(16 + 14)
                draw("\(group.def.label) — due \(Fmt.date(group.dueDate))",
                     at: CGPoint(x: Layout.left, y: y), heading)
                y += 16

                for vaccine in group.def.vaccines {
                    reserve(14)
                    let dose = group.records[vaccine.name]
                    draw(dose == nil ? "[ ]" : "[x]", at: CGPoint(x: 48, y: y), body)
                    draw(vaccine.name, at: CGPoint(x: 74, y: y), body)
                    // Once given, the brand and the date are what a clinic actually needs.
                    let detail = dose.map { d in
                        [d.brand, Fmt.date(d.givenOn), d.clinic]
                            .compactMap { $0 }.filter { !$0.isEmpty }.joined(separator: " · ")
                    } ?? vaccine.description
                    if !detail.isEmpty {
                        draw(detail, at: CGPoint(x: 250, y: y), muted)
                    }
                    y += 14
                }
                y += 8
            }

            if page == 0 { newPage() }
            // Only on the last page, and without a page number: the total is not known until
            // the drawing is done, and "page 2 of 2" written on page 1 would be a lie.
            draw("Generated by Kilkari on \(Fmt.date(.now))",
                 at: CGPoint(x: Layout.left, y: 812), muted)
        }
    }

    private static func draw(
        _ text: String,
        at point: CGPoint,
        _ attributes: [NSAttributedString.Key: Any]
    ) {
        (text as NSString).draw(at: point, withAttributes: attributes)
    }

    private static func rule(at y: CGFloat, in context: UIGraphicsPDFRendererContext) {
        let path = UIBezierPath()
        path.move(to: CGPoint(x: Layout.left, y: y))
        path.addLine(to: CGPoint(x: Layout.right, y: y))
        UIColor(KC.border).setStroke()
        path.lineWidth = 1
        path.stroke()
    }
}
